version: '3'

services:
    webserver:
        image: foecum/web-app:latest
        depends_on:
            - authentication
            - photo
            - vote
            - comment
            - profile
        ports:
            - "4999:4999"
        restart: always
        environment:
        - "affinity:com.mariadb.host!=webserver"
        - "PORT=4999"
        - "PROFILE_URL=http://profile:5000"
        - "AUTHENTICATION_URL=http://authentication:5001"
        - "PHOTO_URL=http://photo:5002"
        - "VOTE_URL=http://vote:5003"
        - "COMMENT_URL=http://comment:5004"
        labels:
        - "com.mariadb.host=webserver"
    authentication:
        image: foecum/auth-svc:latest
        depends_on:
          - servicedb
        ports:
            - "5001:5001"
        restart: always 
        environment:
        - "PORT=5001"
        - "DB_USERNAME=profile_service"
        - "DB_PASSWORD=password"
        - "DB_HOST=database"
        - "DB_PORT=3306"
        - "DB=ProfileService"
        - "SECRET_KEY=ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        - "affinity:com.mariadb.host!=authenticationsvc"
        labels:
        - "com.mariadb.host=authenticationsvc"
    photo:
        image: foecum/photo-svc:latest
        depends_on:
          - servicedb
        ports:
            - "5002:5002"
        restart: always 
        environment:
        - "PORT=5002"
        - "COMMENT_SERVICE_URL=http://comment:5004/"
        - "VOTE_SERVICE_URL=http://vote:5003/"
        - "PROFILE_SERVICE_URL=http://profile:5000/"
        - "DB_USERNAME=photo_service"
        - "DB_PASSWORD=password"
        - "DB_HOST=database"
        - "DB_PORT=3306"
        - "DB=PhotoService"
        - "SECRET_KEY=ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        - "affinity:com.mariadb.host!=photosvc"
        labels:
        - "com.mariadb.host=photosvc"
    vote:
        image: foecum/vote-svc:latest
        depends_on:
          - servicedb
        ports:
            - "5003:5003"
        restart: always
        environment:
        - "PORT=5003"
        - "DB_USERNAME=vote_service"
        - "DB_PASSWORD=password"
        - "DB_HOST=database"
        - "DB_PORT=3306"
        - "DB=VoteService"
        - "SECRET_KEY=ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        - "PHOTO_SERVICE_URL=http://photo:5002/"
        - "affinity:com.mariadb.host!=votesvc"
        labels:
        - "com.mariadb.host=votesvc"
    comment:
        image: foecum/comment-svc:latest
        depends_on:
          - servicedb
        ports:
            - "5004:5004"
        restart: always
        environment:
        - "PORT=5004"
        - "PROFILE_SERVICE_URL=http://profile:5000/"
        - "PHOTO_SERVICE_URL=http://photo:5002/"
        - "VOTE_SERVICE_URL=http://vote:5003/"
        - "DB_USERNAME=comment_service"
        - "DB_PASSWORD=password"
        - "DB_HOST=database"
        - "DB_PORT=3306"
        - "DB=CommentService"
        - "SECRET_KEY=ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        - "affinity:com.mariadb.host!=commentsvc"
        labels:
        - "com.mariadb.host=commentsvc"
    profile:
        image: foecum/profile-svc:latest
        depends_on:
          - servicedb
        ports:
            - "5000:5000"
        restart: always 
        environment:
        - "PORT=5000"
        - "DB_USERNAME=profile_service"
        - "DB_PASSWORD=password"
        - "DB_HOST=database"
        - "DB_PORT=3306"
        - "DB=ProfileService"
        - "SECRET_KEY=ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        - "affinity:com.mariadb.host!=profilesvc"
        labels:
        - "com.mariadb.host=profilesvc"
    servicedb:
        image: foecum/mariadb:latest
        environment:
        - "CLUSTER_NAME=galeracluster"
        - "DISCOVERY_SERVICE=192.168.99.164:2379"
        - "MYSQL_ROOT_PASSWORD=password"
        - "XTRABACKUP_PASSWORD=password"
        - "affinity:com.mariadb.host!=galeracluster"
        labels:
        - "com.mariadb.host=galeracluster"
        ports:
        - 3306:3306
        restart: always 